### PR TITLE
Updating branch from orientation/orientation master 

### PR DESCRIPTION
**Pull request by jmonteiro**
PT: https://www.pivotaltracker.com/story/show/126613995

Updating from https://github.com/orientation/orientation. Major new features:

 - Search is handled by pg_search
 - Rails is at version 5.0

### CODE REVIEW

**Comment by jmonteiro** [comment]
@brupm, @benmanns, @AhmedBelal, @DanielNill and @maletor: please review.

**Comment by brupm** [comment]
Please have @ThomsonT give it some QA love before deploying to prod.
Ensure emails work, either in QA or optionally right after you deploy to prod.  👍 

Awesome work!

**Comment by brupm** [comment]
No need to wait for additional CRs, if QA is good with it, go for ir.

**Comment by SowjanyaEga** [comment]
Ready for deployment.

**Comment by jmonteiro** [comment]
@SowjanyaEga deployed to production.

**Pull request merged**
