### PR TITLE
Switch from Differ to HTMLDiff gem for article update email

### PR DESCRIPTION
**Pull request by Jaym3s**
Differ wasn't behaving well when parsing html & many changes. HTMLDiff gem appears to work better.

### CODE REVIEW

**Comment by Jaym3s** [comment]
https://www.pivotaltracker.com/story/show/113457159

**Comment by Jaym3s** [comment]
@divoxx @brupm @jeyb hopefully the last one for this story :)

**Comment by brupm** [comment]
:+1:

**Comment by karena0619** [comment]
ready for deployment

**Pull request merged**
