### PR TITLE
Convert to sendgrid

### PR DESCRIPTION
**Pull request by Jaym3s**
**QA testing instructions**

- Deploy the app to our QA env on Heroku (dox-orientation-qa.herokuapp.com)
- Subscribe to an article and ask someone else to update it
- Ask someone else to endorse an article you wrote
- Ask someone else to mark an article as rotten

https://www.pivotaltracker.com/story/show/114796731

--------

### TODO

- [x] Pull in Mandrill templates
- [x] Set up sendgrid addon for apps on heroku
- [x] Convert templates to actionmailer templates
- [x] Update mailer to use the new templates
- [ ] ~~Fix tests~~

### CODE REVIEW

**Comment by fgrehm** [comment]
LGTM

**Comment by fgrehm** [comment]
@Jaym3s @brupm this `Works on my Machine` :tm: and I'm about to giving it a try on our QA env. Would you guys be able to have a look at the changes? I'm leaning towards keeping those `ArticleMailer` specs disabled for now.

**Comment by brupm** [comment]
One thing to consider is that this branch will very unlikely be merged back to the upstream. I doubt the maintainer will want to move to sendgrid.

Keeping tests disabled is fine as long as the emails work. :+1:

**Comment by nickwolfe** [comment]
Verified in QA, ready to deploy.

**Pull request merged**
